SCREEN_WIDTH = 640
SCREEN_HEIGHT = 768
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

WORD_LENGTH = 5
NUMBER_OF_TRIES = 6
NUMBER_OF_APLHABETS = 26

FPS = 30

LOG_DIRECTORY = "logs"

EPISODES = 10000
LEARNING_RATE = 0.001
EXPLORATION_RATE = 0.5
DISCOUNT_FACTOR = 0.9

MIN_REWARD = -1
MAX_REWARD = 1
